---

- name: Install software required for kubernetes-the-hard-way
  apt:
    pkg:
      - wget
      - curl
      - vim
      - openssl
      - git
      - tree
    update_cache: yes

- name: Clone the kubernetes-the-hard-way git repo into root home
  git:
    repo: https://github.com/kelseyhightower/kubernetes-the-hard-way.git
    dest: /root/kubernetes-the-hard-way
    depth: 1

- name: Run the download-k8-binaries.sh script on the jumpbox
  script: download-k8-binaries.sh
  args:
    creates: /root/kubernetes-the-hard-way/downloads/worker

- name: Run the create-cert-authority-files.sh script on the jumpbox
  script: create-cert-authority-files.sh
  args:
    creates: /root/kubernetes-the-hard-way/ca.key