---

- name: Install battleshed private ssh key for aws hosts
  copy:
    src: /home/dant/.ssh/battleshed-aws
    dest: /home/admin/.ssh/battleshed-aws
    mode: 0600
    owner: admin
    group: admin

- name: Install software required for kubernetes-the-hard-way
  apt:
    pkg:
      - wget
      - curl
      - vim
      - openssl
      - git
    update_cache: yes
