---

- name: Install battleshed private ssh key for aws hosts
  copy:
    src: /home/dant/.ssh/battleshed-aws
    dest: /home/admin/.ssh/id_rsa
    mode: 0600
    owner: admin
    group: admin

- name: Install software required for kubernetes-the-hard-way
  apt:
    pkg:
      - wget
      - curl
      - vim
      - openssl
      - git
      - tree
    update_cache: yes

- name: Clone the kubernetes-the-hard-way git repo into root home
  git:
    repo: https://github.com/kelseyhightower/kubernetes-the-hard-way.git
    dest: /root/kubernetes-the-hard-way
    depth: 1

- name: Run the download-k8-binaries.sh script on the jumpbox
  script: download-k8-binaries.sh
  args:
    creates: /root/kubernetes-the-hard-way/downloads/worker

- name: Set jumpbox hostname
  hostname:
    name: jumpbox.battleshed.uk
    use: systemd

- name: Add Domain line to /etc/systemd/resolved.conf
  lineinfile:
    path: /etc/systemd/resolved.conf
    insertafter: '^\[Resolve\].*'
    line: Domains=battleshed.uk
  notify:
    - Restart systemd-resolved