---

- name: Install battleshed private ssh key for aws hosts
  copy:
    src: /home/dant/.ssh/battleshed-aws
    dest: /home/admin/.ssh/battleshed-aws
    mode: 0600
    owner: admin
    group: admin

- name: Install software required for kubernetes-the-hard-way
  apt:
    pkg:
      - wget
      - curl
      - vim
      - openssl
      - git
    update_cache: yes

- name: Clone the kubernetes-the-hard-way git repo into root home
  git:
    repo: https://github.com/kelseyhightower/kubernetes-the-hard-way.git
    dest: /root/kubernetes-the-hard-way
    depth: 1

- name: Copy the download-k8-binaries.sh script to jumpbox
  copy:
    src: download-k8-binaries.sh
    dest: /root/kubernetes-the-hard-way
    mode: 0700

- name: Run the download-k8-binaries.sh script
