---

- name: Make kublet directory
  file:
    path: "/var/lib/{{ item }}"
    state: directory
  loop:
    - kubelet
    - kube-proxy

- name: Transfer ca.crt from jumpbox to nodes
  synchronize:
    src: /root/kubernetes-the-hard-way/ca.crt
    dest: /var/lib/kubelet/ca.crt
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer host cert files from jumpbox to nodes
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ inventory_hostname_short }}.crt"
    dest: /var/lib/kubelet/kubelet.crt
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer host key files from jumpbox to nodes
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ inventory_hostname_short }}.key"
    dest: /var/lib/kubelet/kubelet.key
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer kube-proxy.kubeconfig from jumpbox to nodes
  synchronize:
    src: "/root/kubernetes-the-hard-way/kube-proxy.kubeconfig"
    dest: /var/lib/kube-proxy/kubeconfig
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer node kublet kubeconfig from jumpbox to nodes
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ inventory_hostname_short }}.kubeconfig"
    dest: /var/lib/kubelet/kubeconfig
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk