---

- name: Enable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin yes"
    state: present
    backup: yes
  notify:
   - Restart ssh

- name: Set authorized key for root
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/home/dant/.ssh/battleshed-aws.pub') }}"