---

- name: Enable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin yes"
    state: present
    backup: yes
  notify:
   - Restart ssh

- name: Set authorized key for root
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/home/dant/.ssh/battleshed-aws.pub') }}"

- name: Template add_static_routes.sh script
  template:
    src: add_static_routes.sh.j2
    dest: /root/add_static_routes.sh
    mode: 0700

- name: Run the add_static_routes.sh script
  shell: /root/add_static_routes.sh
  args:
    creates: /root/static_routes_added
