---

- name: Transfer certs and keys from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/root/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - ca.key
    - ca.crt
    - kube-api-server.key
    - kube-api-server.crt
    - service-accounts.key
    - service-accounts.crt