---

- name: Transfer certs, keys and config files from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/root/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - ca.key
    - service-accounts.key
    - service-accounts.crt
    - admin.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig
    - encryption-config.yaml

- name: Transfer etcd binary from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/downloads/controller/etcd"
    dest: "/usr/local/bin/etcd"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer etcdctl binary from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/downloads/client/etcdctl"
    dest: "/usr/local/bin/etcdctl"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer etcd.service file from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/units/etcd.service"
    dest: "/etc/systemd/system/etcd.service"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Make /etc/etcd directory
  file:
    path: "/etc/etcd"
    state: directory
    mode: 0700

- name: Make /var/lib/etcd directory
  file:
    path: "/var/lib/etcd"
    state: directory

- name: Configure the etcd server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/etc/etcd/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - ca.crt
    - kube-api-server.key
    - kube-api-server.crt

- name: Enable and start the etcd service
  systemd_service:
    name: etcd
    state: started
    enabled: true
    daemon_reload: true