---

- name: Transfer certs, keys and config files from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/root/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - ca.key
    - ca.crt
    - kube-api-server.key
    - kube-api-server.crt
    - service-accounts.key
    - service-accounts.crt
    - admin.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig
    - encryption-config.yaml

- name: Transfer etcd binaries from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - downloads/controller/etcd
    - downloads/client/etcdctl
