---

- name: Transfer certs, keys and config files from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/root/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - admin.kubeconfig

# Bootstrapping etcd https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md

- name: Transfer etcd binary from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/downloads/controller/etcd"
    dest: "/usr/local/bin/etcd"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer etcdctl binary from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/downloads/client/etcdctl"
    dest: "/usr/local/bin/etcdctl"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer etcd.service file from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/units/etcd.service"
    dest: "/etc/systemd/system/etcd.service"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Make /etc/etcd directory
  file:
    path: "/etc/etcd"
    state: directory
    mode: 0700

- name: Make /var/lib/etcd directory
  file:
    path: "/var/lib/etcd"
    state: directory

- name: Configure the etcd server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/etc/etcd/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - ca.crt
    - kube-api-server.key
    - kube-api-server.crt

- name: Enable and start the etcd service
  systemd_service:
    name: etcd
    state: started
    enabled: true
    daemon_reload: true

# Bootstrapping kubernetes control plane https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md

- name: Make /etc/kubernetes/config directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/kubernetes/config
    - /var/lib/kubernetes/

- name: Transfer kubernetes controller binaries from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/downloads/controller/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Transfer kubectl binaries from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/downloads/client/kubectl"
    dest: "/usr/local/bin/kubectl"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk

- name: Transfer kubernetes API server config from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - ca.crt
    - ca.key
    - kube-api-server.key
    - kube-api-server.crt
    - service-accounts.key
    - service-accounts.crt
    - encryption-config.yaml
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig

- name: Transfer systemd service file from jumpbox to server
  synchronize:
    src: "/root/kubernetes-the-hard-way/units/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    set_remote_user: false
  delegate_to: jumpbox.battleshed.uk
  loop:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service

- name: Enable and start the etcd service
  systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler